on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Comment on PR #${{ github.event.issue.number }}"
          env:
            ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
            github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
            ado_organization: "ranidharan"
            ado_project: "iGABDemoAgile"
            ado_wit: "User Story"
            ado_new_state: "New"
            ado_active_state: "Active"
            ado_close_state: "Closed"
            ado_bypassrules: true
            log_level: 100

  issue_commented:
    # This job only runs for issue comments
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Comment on issue #${{ github.event.issue.number }}"
          env:
            ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
            github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
            ado_organization: "ranidharan"
            ado_project: "iGABDemoAgile"
            ado_wit: "User Story"
            ado_new_state: "New"
            ado_active_state: "Active"
            ado_close_state: "Closed"
            ado_bypassrules: true
            log_level: 100
