name: Update work item state when PR is merged

on:
   pull_request:
    branches: [master]
    types: [closed]

jobs:
  alert:
    runs-on: ubuntu-latest
    name: Test workflow
    steps:       
    - uses: CanarysAutomations/pr-update-work-item-state@master
      env: 
        gh_token : '${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}'   
        ado_token: '${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}'
        ado_organization: 'ranidharan'
        ado_project: 'iGABDemoAgile'
        closedstate: ''
        gh_repo_owner: ''
        gh_repo: ''
        pull_number: '${{github.event.number}}'
